
[env]
TERM = "xterm-256color"

[window]
opacity = 0.96
startup_mode ="Windowed"
decorations_theme_variant = "Dark"

[font]
size = 12

[general]
import = [
	"~/.config/home-manager/alacritty/themes/tokyonight_storm.toml"
]
